spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: haoge2141
    url: jdbc:mysql://localhost:3306/Res_reg_sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
  jdbc:
    template:
      query-timeout: 3
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #驼峰命名